#pragma once

#define ITEM_NONE 0
#define ITEM_MASTER_BALL 1
#define ITEM_ULTRA_BALL 2
#define ITEM_GREAT_BALL 3
#define ITEM_POKE_BALL 4
#define ITEM_SAFARI_BALL 5
#define ITEM_NET_BALL 6
#define ITEM_DIVE_BALL 7
#define ITEM_NEST_BALL 8
#define ITEM_REPEAT_BALL 9
#define ITEM_TIMER_BALL 10
#define ITEM_LUXURY_BALL 11
#define ITEM_PREMIER_BALL 12
#define ITEM_POTION 13
#define ITEM_ANTIDOTE 14
#define ITEM_BURN_HEAL 15
#define ITEM_ICE_HEAL 16
#define ITEM_AWAKENING 17
#define ITEM_PARALYZE_HEAL 18
#define ITEM_FULL_RESTORE 19
#define ITEM_MAX_POTION 20
#define ITEM_HYPER_POTION 21
#define ITEM_SUPER_POTION 22
#define ITEM_FULL_HEAL 23
#define ITEM_REVIVE 24
#define ITEM_MAX_REVIVE 25
#define ITEM_FRESH_WATER 26
#define ITEM_SODA_POP 27
#define ITEM_LEMONADE 28
#define ITEM_MOOMOO_MILK 29
#define ITEM_ENERGY_POWDER 30
#define ITEM_ENERGY_ROOT 31
#define ITEM_HEAL_POWDER 32
#define ITEM_REVIVAL_HERB 33
#define ITEM_ETHER 34
#define ITEM_MAX_ETHER 35
#define ITEM_ELIXIR 36
#define ITEM_MAX_ELIXIR 37
#define ITEM_LAVA_COOKIE 38
#define ITEM_BLUE_FLUTE 39
#define ITEM_YELLOW_FLUTE 40
#define ITEM_RED_FLUTE 41
#define ITEM_BLACK_FLUTE 42
#define ITEM_WHITE_FLUTE 43
#define ITEM_BERRY_JUICE 44
#define ITEM_SACRED_ASH 45
#define ITEM_SHOAL_SALT 0xFFFE
#define ITEM_SHOAL_SHELL 0xFFFE
#define ITEM_RED_SHARD 48
#define ITEM_BLUE_SHARD 49
#define ITEM_YELLOW_SHARD 50
#define ITEM_GREEN_SHARD 51
#define ITEM_034 0xFFFE
#define ITEM_035 0xFFFE
#define ITEM_036 0xFFFE
#define ITEM_037 0xFFFE
#define ITEM_038 0xFFFE
#define ITEM_039 0xFFFE
#define ITEM_03A 0xFFFE
#define ITEM_03B 0xFFFE
#define ITEM_03C 0xFFFE
#define ITEM_03D 0xFFFE
#define ITEM_03E 0xFFFE
#define ITEM_HP_UP 63
#define ITEM_PROTEIN 64
#define ITEM_IRON 65
#define ITEM_CARBOS 66
#define ITEM_CALCIUM 67
#define ITEM_RARE_CANDY 68
#define ITEM_PP_UP 69
#define ITEM_ZINC 70
#define ITEM_PP_MAX 71
#define ITEM_048 72
#define ITEM_GUARD_SPEC 73
#define ITEM_DIRE_HIT 74
#define ITEM_X_ATTACK 75
#define ITEM_X_DEFEND 76
#define ITEM_X_SPEED 77
#define ITEM_X_ACCURACY 78
#define ITEM_X_SPECIAL 79
#define ITEM_POKE_DOLL 80
#define ITEM_FLUFFY_TAIL 81
#define ITEM_052 82
#define ITEM_SUPER_REPEL 83
#define ITEM_MAX_REPEL 84
#define ITEM_ESCAPE_ROPE 85
#define ITEM_REPEL 86
#define ITEM_057 87
#define ITEM_058 88
#define ITEM_059 89
#define ITEM_05A 90
#define ITEM_05B 91
#define ITEM_05C 92
#define ITEM_SUN_STONE 93
#define ITEM_MOON_STONE 94
#define ITEM_FIRE_STONE 95
#define ITEM_THUNDER_STONE 96
#define ITEM_WATER_STONE 97
#define ITEM_LEAF_STONE 98
#define ITEM_063 99
#define ITEM_064 100
#define ITEM_065 101
#define ITEM_066 102
#define ITEM_TINY_MUSHROOM 103
#define ITEM_BIG_MUSHROOM 104
#define ITEM_069 105
#define ITEM_PEARL 106
#define ITEM_BIG_PEARL 107
#define ITEM_STARDUST 108
#define ITEM_STAR_PIECE 109
#define ITEM_NUGGET 110
#define ITEM_HEART_SCALE 111
#define ITEM_070 112
#define ITEM_071 113
#define ITEM_072 114
#define ITEM_073 115
#define ITEM_074 116
#define ITEM_075 117
#define ITEM_076 118
#define ITEM_077 119
#define ITEM_078 120
#define ITEM_ORANGE_MAIL 0xFFFE
#define ITEM_HARBOR_MAIL 0xFFFE
#define ITEM_GLITTER_MAIL 0xFFFE
#define ITEM_MECH_MAIL 0xFFFE
#define ITEM_WOOD_MAIL 0xFFFE
#define ITEM_WAVE_MAIL 0xFFFE
#define ITEM_BEAD_MAIL 0xFFFE
#define ITEM_SHADOW_MAIL 0xFFFE
#define ITEM_TROPIC_MAIL 0xFFFE
#define ITEM_DREAM_MAIL 0xFFFE
#define ITEM_FAB_MAIL 0xFFFE
#define ITEM_RETRO_MAIL 0xFFFE
#define ITEM_CHERI_BERRY 133
#define ITEM_CHESTO_BERRY 134
#define ITEM_PECHA_BERRY 135
#define ITEM_RAWST_BERRY 136
#define ITEM_ASPEAR_BERRY 137
#define ITEM_LEPPA_BERRY 138
#define ITEM_ORAN_BERRY 139
#define ITEM_PERSIM_BERRY 140
#define ITEM_LUM_BERRY 141
#define ITEM_SITRUS_BERRY 142
#define ITEM_FIGY_BERRY 143
#define ITEM_WIKI_BERRY 144
#define ITEM_MAGO_BERRY 145
#define ITEM_AGUAV_BERRY 146
#define ITEM_IAPAPA_BERRY 147
#define ITEM_RAZZ_BERRY 0xFFFE
#define ITEM_BLUK_BERRY 0xFFFE
#define ITEM_NANAB_BERRY 0xFFFE
#define ITEM_WEPEAR_BERRY 0xFFFE
#define ITEM_PINAP_BERRY 0xFFFE
#define ITEM_POMEG_BERRY 0x1AC
#define ITEM_KELPSY_BERRY 0x1AD
#define ITEM_QUALOT_BERRY 0x1AE
#define ITEM_HONDEW_BERRY 0x1AF
#define ITEM_GREPA_BERRY 0x1B0
#define ITEM_TAMATO_BERRY 0x1B1
#define ITEM_CORNN_BERRY 0xFFFE
#define ITEM_MAGOST_BERRY 0xFFFE
#define ITEM_RABUTA_BERRY 0xFFFE
#define ITEM_NOMEL_BERRY 0xFFFE
#define ITEM_SPELON_BERRY 0xFFFE
#define ITEM_PAMTRE_BERRY 0xFFFE
#define ITEM_WATMEL_BERRY 0xFFFE
#define ITEM_DURIN_BERRY 0xFFFE
#define ITEM_BELUE_BERRY 0xFFFE
#define ITEM_LIECHI_BERRY 168
#define ITEM_GANLON_BERRY 169
#define ITEM_SALAC_BERRY 170
#define ITEM_PETAYA_BERRY 171
#define ITEM_APICOT_BERRY 172
#define ITEM_LANSAT_BERRY 173
#define ITEM_STARF_BERRY 174
#define ITEM_ENIGMA_BERRY_OLD 0xAF
#define ITEM_ENIGMA_BERRY ITEM_ENIGMA_BERRY_OLD
#define ITEM_0B0 176
#define ITEM_0B1 177
#define ITEM_0B2 178
#define ITEM_BRIGHT_POWDER 179
#define ITEM_WHITE_HERB 180
#define ITEM_MACHO_BRACE 181
#define ITEM_EXP_SHARE 182
#define ITEM_QUICK_CLAW 183
#define ITEM_SOOTHE_BELL 184
#define ITEM_MENTAL_HERB 185

#ifdef UNBOUND
#define ITEM_CHOICE_BAND 0xB0 //For Unbound
#else
#define ITEM_CHOICE_BAND 186
#endif

#define ITEM_KINGS_ROCK 58
#define ITEM_SILVER_POWDER 188
#define ITEM_AMULET_COIN 189
#define ITEM_CLEANSE_TAG 190
#define ITEM_SOUL_DEW 191
#define ITEM_DEEP_SEA_TOOTH 192
#define ITEM_DEEP_SEA_SCALE 193
#define ITEM_SMOKE_BALL 194
#define ITEM_EVERSTONE 195
#define ITEM_FOCUS_BAND 196
#define ITEM_LUCKY_EGG 197
#define ITEM_SCOPE_LENS 198
#define ITEM_METAL_COAT 59
#define ITEM_LEFTOVERS 200
#define ITEM_DRAGON_SCALE 201
#define ITEM_LIGHT_BALL 202
#define ITEM_SOFT_SAND 203
#define ITEM_HARD_STONE 204
#define ITEM_MIRACLE_SEED 205
#define ITEM_BLACK_GLASSES 206
#define ITEM_BLACK_BELT 207
#define ITEM_MAGNET 208
#define ITEM_MYSTIC_WATER 209
#define ITEM_SHARP_BEAK 210
#define ITEM_POISON_BARB 211
#define ITEM_NEVER_MELT_ICE 212
#define ITEM_SPELL_TAG 213
#define ITEM_TWISTED_SPOON 214
#define ITEM_CHARCOAL 215
#define ITEM_DRAGON_FANG 216
#define ITEM_SILK_SCARF 217
#define ITEM_UP_GRADE 60
#define ITEM_SHELL_BELL 219
#define ITEM_SEA_INCENSE 220
#define ITEM_LAX_INCENSE 221
#define ITEM_LUCKY_PUNCH 222
#define ITEM_METAL_POWDER 223
#define ITEM_THICK_CLUB 224
#define ITEM_LEEK 225
#define ITEM_0E2 226
#define ITEM_0E3 227
#define ITEM_0E4 228
#define ITEM_0E5 229
#define ITEM_0E6 230
#define ITEM_0E7 231
#define ITEM_0E8 232
#define ITEM_0E9 233
#define ITEM_0EA 234
#define ITEM_0EB 235
#define ITEM_0EC 236
#define ITEM_0ED 237
#define ITEM_0EE 238
#define ITEM_0EF 239
#define ITEM_0F0 240
#define ITEM_0F1 241
#define ITEM_0F2 242
#define ITEM_0F3 243
#define ITEM_0F4 244
#define ITEM_0F5 245
#define ITEM_0F6 246
#define ITEM_0F7 247
#define ITEM_0F8 248
#define ITEM_0F9 249
#define ITEM_0FA 250
#define ITEM_0FB 251
#define ITEM_0FC 252
#define ITEM_0FD 253
#define ITEM_RED_SCARF 0xFFFE
#define ITEM_BLUE_SCARF 0xFFFE
#define ITEM_PINK_SCARF 0xFFFE
#define ITEM_GREEN_SCARF 0xFFFE
#define ITEM_YELLOW_SCARF 0xFFFE
#define ITEM_MACH_BIKE 0xFFFE
#define ITEM_COIN_CASE 260
#define ITEM_ITEMFINDER 261
#define ITEM_OLD_ROD 262
#define ITEM_GOOD_ROD 263
#define ITEM_SUPER_ROD 264
#define ITEM_SS_TICKET 265
#define ITEM_CONTEST_PASS 0xFFFE
#define ITEM_10B 267
#define ITEM_WAILMER_PAIL 268
#define ITEM_DEVON_GOODS 269
#define ITEM_SOOT_SACK 270
#define ITEM_BASEMENT_KEY 271
#define ITEM_ACRO_BIKE 272
#define ITEM_POKEBLOCK_CASE 273
#define ITEM_LETTER 274
#define ITEM_EON_TICKET 275
#define ITEM_RED_ORB 276
#define ITEM_BLUE_ORB 277
#define ITEM_SCANNER 278
#define ITEM_GO_GOGGLES 279
#define ITEM_METEORITE 280
#define ITEM_ROOM_1_KEY 0xFFFE
#define ITEM_ROOM_2_KEY 0xFFFE
#define ITEM_ROOM_4_KEY 0xFFFE
#define ITEM_ROOM_6_KEY 0xFFFE
#define ITEM_STORAGE_KEY 0xFFFE
#define ITEM_ROOT_FOSSIL 286
#define ITEM_CLAW_FOSSIL 287
#define ITEM_DEVON_SCOPE 288
#define ITEM_TM01 289
#define ITEM_TM02 290
#define ITEM_TM03 291
#define ITEM_TM04 292
#define ITEM_TM05 293
#define ITEM_TM06 294
#define ITEM_TM07 295
#define ITEM_TM08 296
#define ITEM_TM09 297
#define ITEM_TM10 298
#define ITEM_TM11 299
#define ITEM_TM12 300
#define ITEM_TM13 301
#define ITEM_TM14 302
#define ITEM_TM15 303
#define ITEM_TM16 304
#define ITEM_TM17 305
#define ITEM_TM18 306
#define ITEM_TM19 307
#define ITEM_TM20 308
#define ITEM_TM21 309
#define ITEM_TM22 310
#define ITEM_TM23 311
#define ITEM_TM24 312
#define ITEM_TM25 313
#define ITEM_TM26 314
#define ITEM_TM27 315
#define ITEM_TM28 316
#define ITEM_TM29 317
#define ITEM_TM30 318
#define ITEM_TM31 319
#define ITEM_TM32 320
#define ITEM_TM33 321
#define ITEM_TM34 322
#define ITEM_TM35 323
#define ITEM_TM36 324
#define ITEM_TM37 325
#define ITEM_TM38 326
#define ITEM_TM39 327
#define ITEM_TM40 328
#define ITEM_TM41 329
#define ITEM_TM42 330
#define ITEM_TM43 331
#define ITEM_TM44 332
#define ITEM_TM45 333
#define ITEM_TM46 334
#define ITEM_TM47 335
#define ITEM_TM48 336
#define ITEM_TM49 337
#define ITEM_TM50 338
#define ITEM_HM01 339
#define ITEM_HM02 340
#define ITEM_HM03 341
#define ITEM_HM04 342
#define ITEM_HM05 343
#define ITEM_HM06 344
#define ITEM_HM07 345
#define ITEM_HM08 346
#define ITEM_15B 347
#define ITEM_15C 348

//New TMs
#define ITEM_TM51 348
#define ITEM_TM52 121
#define ITEM_TM53 122
#define ITEM_TM54 0xFFFE
#define ITEM_TM55 0xFFFE
#define ITEM_TM56 123
#define ITEM_TM57 124
#define ITEM_TM58 0xFFFE
#define ITEM_TM59 347
#define ITEM_TM60 267 //comeback
#define ITEM_TM61 126
#define ITEM_TM62 0xFFFE
#define ITEM_TM63 0x11A
#define ITEM_TM64 0xFFFE
#define ITEM_TM65 127
#define ITEM_TM66 0xFFFE
#define ITEM_TM67 0xFFFE
#define ITEM_TM68 0xFFFE
#define ITEM_TM69 0xFFFE
#define ITEM_TM70 0xFFFE
#define ITEM_TM71 128
#define ITEM_TM72 0xFFFE
#define ITEM_TM73 129
#define ITEM_TM74 130
#define ITEM_TM75 132
#define ITEM_TM76 157
#define ITEM_TM77 158
#define ITEM_TM78 0xFFFE
#define ITEM_TM79 159
#define ITEM_TM80 160
#define ITEM_TM81 161
#define ITEM_TM82 0xFFFE
#define ITEM_TM83 162
#define ITEM_TM84 163
#define ITEM_TM85 0xFFFE
#define ITEM_TM86 164
#define ITEM_TM87 0xFFFE
#define ITEM_TM88 0xFFFE
#define ITEM_TM89 165
#define ITEM_TM90 442
#define ITEM_TM91 166
#define ITEM_TM92 167
#define ITEM_TM93 0xFFFE
#define ITEM_TM94 0xFFFE
#define ITEM_TM95 0xFFFE
#define ITEM_TM96 0xFFFE
#define ITEM_TM97 0xFFFE
#define ITEM_TM98 0xFFFE
#define ITEM_TM99 427
#define ITEM_TM100 0xFFFE
#define ITEM_TM101 46
#define ITEM_TM102 47
#define ITEM_TM103 218
#define ITEM_TM104 259
#define ITEM_TM105 0xFFFE
#define ITEM_TM106 0xFFFE
#define ITEM_TM107 0xFFFE
#define ITEM_TM108 0xFFFE
#define ITEM_TM109 0xFFFE
#define ITEM_TM110 0xFFFE
#define ITEM_TM111 0xFFFE
#define ITEM_TM112 0xFFFE
#define ITEM_TM113 0xFFFE
#define ITEM_TM114 0xFFFE
#define ITEM_TM115 0xFFFE
#define ITEM_TM116 443
#define ITEM_TM117 0xFFFE
#define ITEM_TM118 0xFFFE
#define ITEM_TM119 0xFFFE
#define ITEM_TM120 0xFFFE

// FireRed/LeafGreen
#define ITEM_OAKS_PARCEL 349
#define ITEM_POKE_FLUTE 350
#define ITEM_SECRET_KEY 351
#define ITEM_BIKE_VOUCHER 352
#define ITEM_GOLD_TEETH 353
#define ITEM_OLD_AMBER 354
#define ITEM_CARD_KEY 355
#define ITEM_LIFT_KEY 356
#define ITEM_HELIX_FOSSIL 357
#define ITEM_DOME_FOSSIL 358
#define ITEM_SILPH_SCOPE 359
#define ITEM_BICYCLE 360
#define ITEM_TOWN_MAP 361
#define ITEM_VS_SEEKER 362
#define ITEM_FAME_CHECKER 363
#define ITEM_TM_CASE 364
#define ITEM_BERRY_POUCH 365
#define ITEM_TEACHY_TV 366
#define ITEM_TRI_PASS 367
#define ITEM_RAINBOW_PASS 368
#define ITEM_TEA 369
#define ITEM_MYSTIC_TICKET 370
#define ITEM_AURORA_TICKET 371
#define ITEM_POWDER_JAR 372
#define ITEM_RUBY 373
#define ITEM_SAPPHIRE 374

//New Sellable Items
#define ITEM_RARE_BONE 0xFFFE
#define ITEM_PEARL_STRING 0xFFFE
#define ITEM_BIG_NUGGET 0x1B4
#define ITEM_COMET_SHARD 0xFFFE
#define ITEM_BALM_MUSHROOM 0xFFFE

//New Food Items
#define ITEM_HONEY 0x1B3
#define ITEM_BIG_MALASADA 0xFFFE
#define ITEM_CASTELIACONE 0xFFFE
#define ITEM_LUMIOSE_GALETTE 0xFFFE
#define ITEM_RAGE_CANDY_BAR 0xFFFE
#define ITEM_SHALOUR_SABLE 0xFFFE
#define ITEM_OLD_GATEAU 0xFFFE

//Fossils
#define ITEM_SKULL_FOSSIL 0x179
#define ITEM_ARMOR_FOSSIL 0x17A
#define ITEM_COVER_FOSSIL 0x17B
#define ITEM_PLUME_FOSSIL 0x17C
#define ITEM_JAW_FOSSIL 0x17D
#define ITEM_SAIL_FOSSIL 0x17E

//EV Gain Items
#define ITEM_POWER_BRACER 0x17F
#define ITEM_POWER_BELT 0x180
#define ITEM_POWER_LENS 0x181
#define ITEM_POWER_BAND 0x182
#define ITEM_POWER_ANKLET 0x183
#define ITEM_POWER_WEIGHT 0x184

//New Battle Hold Items
#define ITEM_ADAMANT_ORB 0x187
#define ITEM_LUSTROUS_ORB 0x188
#define ITEM_GRISEOUS_ORB 0x189

#define ITEM_EXPERT_BELT 0x64
#define ITEM_POWER_HERB 0x1B5
#define ITEM_WIDE_LENS 0xBB
#define ITEM_ZOOM_LENS 0xFFFE
#define ITEM_DESTINY_KNOT 0x1A5 //need this
#define ITEM_SMOOTH_ROCK 0x9B
#define ITEM_DAMP_ROCK 0x98
#define ITEM_HEAT_ROCK 0x99
#define ITEM_ICY_ROCK 0x9A
#define ITEM_BIG_ROOT 0x18A
#define ITEM_LIGHT_CLAY 0x3E
#define ITEM_SAFETY_GOGGLES 0x9C
#define ITEM_ROCKY_HELMET 0xB2
#define ITEM_WEAKNESS_POLICY 0x96
#define ITEM_ASSAULT_VEST 0x97
#define ITEM_EVIOLITE 0xB1
#define ITEM_ABSORB_BULB 0x1B6
#define ITEM_AIR_BALLOON 0x3D
#define ITEM_ADRENALINE_ORB 0xFFFE
#define ITEM_BINDING_BAND 0xFFFE
#define ITEM_CELL_BATTERY 0xFFFE
#define ITEM_EJECT_BUTTON 0x18B
#define ITEM_FLOAT_STONE 0xFFFE
#define ITEM_FOCUS_SASH 0xB0
#define ITEM_GRIP_CLAW 0xFFFE
#define ITEM_IRON_BALL 0x185
#define ITEM_LAGGING_TAIL 0xFFFE
#define ITEM_LUMINOUS_MOSS 0xFFFE
#define ITEM_QUICK_POWDER 0xFFFE
#define ITEM_METRONOME 0x186
#define ITEM_MUSCLE_BAND 0x18C
#define ITEM_PROTECTIVE_PADS 0xFFFE
#define ITEM_RED_CARD 0x18E
#define ITEM_RING_TARGET 0xFFFE
#define ITEM_SHED_SHELL 0x1B7
#define ITEM_SNOWBALL 0xFFFE
#define ITEM_STICKY_BARB 0xFFFE
#define ITEM_TERRAIN_EXTENDER 0x1B2
#define ITEM_WISE_GLASSES 0x18D
#define ITEM_ELECTRIC_SEED 0x18F
#define ITEM_GRASSY_SEED 0x190
#define ITEM_MISTY_SEED 0x191
#define ITEM_PSYCHIC_SEED 0x192

#define ITEM_LIFE_ORB 0x69
#define ITEM_TOXIC_ORB 0x94
#define ITEM_FLAME_ORB 0x95
#define ITEM_BLACK_SLUDGE 0x65

#define ITEM_CHOICE_SPECS 0x63
#define ITEM_CHOICE_SCARF 0x66

//New Incense
#define ITEM_LUCK_INCENSE 0xFC
#define ITEM_FULL_INCENSE 0xFD
#define ITEM_ODD_INCENSE 0xFE
#define ITEM_PURE_INCENSE 0xFF
#define ITEM_ROCK_INCENSE 0x100
#define ITEM_ROSE_INCENSE 0x101
#define ITEM_WAVE_INCENSE 0x102

//Gems
#define ITEM_NORMAL_GEM 0xFFFE
#define ITEM_FIGHTING_GEM 0xFFFE
#define ITEM_FLYING_GEM 0xFFFE
#define ITEM_POISON_GEM 0xFFFE
#define ITEM_GROUND_GEM 0xFFFE
#define ITEM_ROCK_GEM 0xFFFE
#define ITEM_BUG_GEM 0xFFFE
#define ITEM_GHOST_GEM 0xFFFE
#define ITEM_STEEL_GEM 0xFFFE
#define ITEM_FIRE_GEM 0xFFFE
#define ITEM_WATER_GEM 0xFFFE
#define ITEM_GRASS_GEM 0xFFFE
#define ITEM_ELECTRIC_GEM 0xFFFE
#define ITEM_PSYCHIC_GEM 0xFFFE
#define ITEM_ICE_GEM 0xFFFE
#define ITEM_DRAGON_GEM 0xFFFE
#define ITEM_DARK_GEM 0xFFFE
#define ITEM_FAIRY_GEM 0xFFFE

//Arceus Plates
#define ITEM_FIST_PLATE 0xFFFE
#define ITEM_SKY_PLATE 0xFFFE
#define ITEM_TOXIC_PLATE 0xFFFE
#define ITEM_EARTH_PLATE 0xFFFE
#define ITEM_STONE_PLATE 0xFFFE
#define ITEM_INSECT_PLATE 0xFFFE
#define ITEM_SPOOKY_PLATE 0xFFFE
#define ITEM_IRON_PLATE 0xC7
#define ITEM_FLAME_PLATE 0xFFFE
#define ITEM_SPLASH_PLATE 0xFFFE
#define ITEM_MEADOW_PLATE 0xFFFE
#define ITEM_ZAP_PLATE 0xFFFE
#define ITEM_MIND_PLATE 0xFFFE
#define ITEM_ICICLE_PLATE 0xFFFE
#define ITEM_DRACO_PLATE 0xFFFE
#define ITEM_DREAD_PLATE 0xFFFE
#define ITEM_PIXIE_PLATE 0x1B8


//Mega Stones
#define ITEM_MEGA_RING 0xE2

#define ITEM_ULTRANECROZIUM_Z 0xFFFE
#define ITEM_VENUSAURITE 0xE4
#define ITEM_CHARIZARDITE_X 0xE5
#define ITEM_CHARIZARDITE_Y 0xE6
#define ITEM_BLASTOISINITE 0xE7
#define ITEM_BEEDRILLITE 0xE8
#define ITEM_PIDGEOTITE 0xE9
#define ITEM_ALAKAZITE 0xE3
#define ITEM_SLOWBRONITE 0xEA
#define ITEM_GENGARITE 0x52
#define ITEM_KANGASKHANITE 0xEB
#define ITEM_PINSIRITE 0xEC
#define ITEM_GYARADOSITE 0xED
#define ITEM_AERODACTYLITE 0xEE
#define ITEM_MEWTWONITE_X 0xEF
#define ITEM_MEWTWONITE_Y 0xF0
#define ITEM_AMPHAROSITE 0xF1
#define ITEM_STEELIXITE 0xF2
#define ITEM_SCIZORITE 0xF3
#define ITEM_HERACRONITE 0xF4
#define ITEM_HOUNDOOMINITE 0xF5
#define ITEM_TYRANITARITE 0xF6
#define ITEM_SCEPTILITE 0xF7
#define ITEM_BLAZIKENITE 0xF8
#define ITEM_SWAMPERTITE 0xF9
#define ITEM_GARDEVOIRITE 0xFA
#define ITEM_SABLENITE 0xFB
#define ITEM_MAWILITE 0xFC
#define ITEM_AGGRONITE 0xFD
#define ITEM_MEDICHAMITE 0xFE
#define ITEM_MANECTITE 0xFF
#define ITEM_SHARPEDONITE 0x100
#define ITEM_CAMERUPTITE 0x101
#define ITEM_ALTARIANITE 0x102
#define ITEM_BANETTITE 0x70
#define ITEM_ABSOLITE 0x71
#define ITEM_GLALITITE 0x72
#define ITEM_SALAMENCITE 0x73
#define ITEM_METAGROSSITE 0x74
#define ITEM_LATIASITE 0x75
#define ITEM_LATIOSITE 0x76
#define ITEM_LOPUNNITE 0x77
#define ITEM_GARCHOMPITE 0x78
#define ITEM_LUCARIONITE 0x57
#define ITEM_ABOMASITE 0x58
#define ITEM_GALLADITE 0x59
#define ITEM_AUDINITE 0x5A
#define ITEM_DIANCITE 0x5B
#define ITEM_BUTTERFREEITE_X 0x1BF
#define ITEM_MACHAMPITE 0x1C0
#define ITEM_KINGLERITE 0x1C1
#define ITEM_SNORLAXITE 0x11B
#define ITEM_GARBODORITE 0x11C
#define ITEM_LAPRASITE 0x11D

//Type-Resist + New Berries
#define ITEM_OCCA_BERRY 0x193
#define ITEM_PASSHO_BERRY 0x194
#define ITEM_WACAN_BERRY 0x195
#define ITEM_RINDO_BERRY 0x196
#define ITEM_YACHE_BERRY 0x197
#define ITEM_CHOPLE_BERRY 0x198
#define ITEM_KEBIA_BERRY 0x199
#define ITEM_SHUCA_BERRY 0x19A
#define ITEM_COBA_BERRY 0x19B
#define ITEM_PAYAPA_BERRY 0x19C
#define ITEM_TANGA_BERRY 0x19D
#define ITEM_CHARTI_BERRY 0x19E
#define ITEM_KASIB_BERRY 0x19F
#define ITEM_HABAN_BERRY 0x1A0
#define ITEM_COLBUR_BERRY 0x1A1
#define ITEM_BABIRI_BERRY 0x1A2
#define ITEM_CHILAN_BERRY 0x1A3
#define ITEM_MICLE_BERRY 0xFFFE
#define ITEM_CUSTAP_BERRY 0xFFFE
#define ITEM_JABOCA_BERRY 0xFFFE
#define ITEM_ROWAP_BERRY 0xFFFE
#define ITEM_ROSELI_BERRY 0x1A4
#define ITEM_KEE_BERRY 0xFFFE
#define ITEM_MARANGA_BERRY 0xFFFE

//New Poke Balls
#define ITEM_PARK_BALL 0xFFFE
#define ITEM_CHERISH_BALL 0xFFFE
#define ITEM_DUSK_BALL 0x83
#define ITEM_HEAL_BALL 0xFFFE
#define ITEM_QUICK_BALL 0x7D
#define ITEM_FAST_BALL 0xFFFE
#define ITEM_LEVEL_BALL 0xFFFE
#define ITEM_LURE_BALL 0xFFFE
#define ITEM_HEAVY_BALL 0xFFFE
#define ITEM_LOVE_BALL 0xFFFE
#define ITEM_FRIEND_BALL 0xFFFE
#define ITEM_MOON_BALL 0xFFFE
#define ITEM_SPORT_BALL 0xFFFE
#define ITEM_BEAST_BALL 0xFFFE
#define ITEM_DREAM_BALL 0x10A

//Genesect Drives
#define ITEM_BURN_DRIVE 0x1A6
#define ITEM_DOUSE_DRIVE 0x1A7
#define ITEM_SHOCK_DRIVE 0x1A8
#define ITEM_CHILL_DRIVE 0x1A9

//Silvally Memories
#define ITEM_FIGHTING_MEMORY 0xFFFE
#define ITEM_FLYING_MEMORY 0xFFFE
#define ITEM_POISON_MEMORY 0xFFFE
#define ITEM_GROUND_MEMORY 0xFFFE
#define ITEM_ROCK_MEMORY 0xFFFE
#define ITEM_BUG_MEMORY 0xFFFE
#define ITEM_GHOST_MEMORY 0xFFFE
#define ITEM_STEEL_MEMORY 0xFFFE
#define ITEM_FIRE_MEMORY 0xFFFE
#define ITEM_WATER_MEMORY 0xFFFE
#define ITEM_GRASS_MEMORY 0xFFFE
#define ITEM_ELECTRIC_MEMORY 0xFFFE
#define ITEM_PSYCHIC_MEMORY 0xFFFE
#define ITEM_ICE_MEMORY 0xFFFE
#define ITEM_DRAGON_MEMORY 0xFFFE
#define ITEM_DARK_MEMORY 0xFFFE
#define ITEM_FAIRY_MEMORY 0xFFFE

//Wings
#define ITEM_HEALTH_WING 0xFFFE
#define ITEM_MUSCLE_WING 0xFFFE
#define ITEM_RESIST_WING 0xFFFE
#define ITEM_GENIUS_WING 0xFFFE
#define ITEM_CLEVER_WING 0xFFFE
#define ITEM_SWIFT_WING 0xFFFE
#define ITEM_PRETTY_WING 0xFFFE


//Random Normal Items
#define ITEM_ODD_KEYSTONE 0xFFFE
#define ITEM_BOTTLE_CAP 0x1AA
#define ITEM_GOLD_BOTTLE_CAP 0xFFFE
#define ITEM_ABILITY_CAPSULE 0xFFFE
#define ITEM_WISHING_PIECE 0xFFFE

//Nectars
#define ITEM_RED_NECTAR 0xFFF0
#define ITEM_YELLOW_NECTAR 0xFFF1
#define ITEM_PINK_NECTAR 0xFFF2
#define ITEM_PURPLE_NECTAR 0xFFF3

//Evolution Items
#define ITEM_LINK_STONE 0x34 //testing something...
#define ITEM_DUSK_STONE 0x36
#define ITEM_DAWN_STONE 0x37
#define ITEM_SHINY_STONE 0x35
#define ITEM_OVAL_STONE 0xFFFE
#define ITEM_ICE_STONE 0x38

#define ITEM_PROTECTOR 0xFFFE
#define ITEM_MAGMARIZER 0xFFFE
#define ITEM_PRISM_SCALE 0x39
#define ITEM_SACHET 0xFFFE
#define ITEM_WHIPPED_DREAM 0xFFFE
#define ITEM_RAZOR_CLAW 0xFFFE
#define ITEM_RAZOR_FANG 0xFFFE
#define ITEM_REAPER_CLOTH 0xFFFE
#define ITEM_DUBIOUS_DISC 0xFFFE
#define ITEM_ELECTIRIZER 0xFFFE

//New Key Items
#define ITEM_GRACIDEA 0xFFFE
#define ITEM_DNA_SPLICERS 0xFFFE
#define ITEM_REVEAL_GLASS 0xFFFE
#define ITEM_PRISON_BOTTLE 0xFFFE

#define ITEM_OVAL_CHARM 0x1B9
#define ITEM_SHINY_CHARM 0x5C
#define ITEM_RAINBOW_WING 0xFFFE
#define ITEM_SILVER_WING 0xFFFE
#define ITEM_MAGMA_STONE 0xFFFE
#define ITEM_N_SOLARIZER 0x178
#define ITEM_N_LUNARIZER 0x1C1
#define ITEM_SUN_FLUTE 0xFFFE
#define ITEM_MOON_FLUTE 0xFFFE
#define ITEM_LIGHT_STONE 0xFFFE
#define ITEM_DARK_STONE 0xFFFE

#define ITEM_DYNAMAX_BAND 0x119

//Relic Items
#define ITEM_RELIC_COPPER 0xFFFE
#define ITEM_RELIC_SILVER 0xFFFE
#define ITEM_RELIC_GOLD 0xFFFE
#define ITEM_RELIC_VASE 0xFFFE
#define ITEM_RELIC_BAND 0xFFFE
#define ITEM_RELIC_STATUE 0xFFFE
#define ITEM_RELIC_CROWN 0xFFFE

//Z-Crystals
enum
{
	ITEM_NORMALIUM_Z = 0xFFFE, 		//All items after this will be 0x29E + 1, 0x29E + 2...
	ITEM_FIGHTINIUM_Z = 0xFFFE, 		//0x29F //Put the Z-Crystals in order
	ITEM_FLYINIUM_Z = 0xFFFE,		//0x2A0
	ITEM_POISONIUM_Z = 0xFFFE,		//0x2A1
	ITEM_GROUNDIUM_Z = 0xFFFE,		//0x2A2
	ITEM_ROCKIUM_Z = 0xFFFE,			//0x2A3
	ITEM_BUGINIUM_Z = 0xFFFE,		//0x2A4
	ITEM_GHOSTIUM_Z = 0xFFFE,		//0x2A5
	ITEM_STEELIUM_Z = 0xFFFE,		//0x2A6
	ITEM_FIRIUM_Z = 0xFFFE,			//0x2A7
	ITEM_WATERIUM_Z = 0xFFFE,		//0x2A8
	ITEM_GRASSIUM_Z = 0xFFFE,		//0x2A9
	ITEM_ELECTRIUM_Z = 0xFFFE,		//0x2AA
	ITEM_PSYCHIUM_Z = 0xFFFE,		//0x2AB
	ITEM_ICIUM_Z = 0xFFFE,			//0x2AC
	ITEM_DRAGONIUM_Z = 0xFFFE,		//0x2AD
	ITEM_DARKINIUM_Z = 0xFFFE,		//0x2AE
	ITEM_FAIRIUM_Z = 0xFFFE,			//0x2AF
	ITEM_ALORAICHIUM_Z = 0xFFFE,		//0x2B0
	ITEM_DECIDIUM_Z = 0xFFFE,		//0x2B1
	ITEM_EEVIUM_Z = 0xFFFE,			//0x2B2
	ITEM_INCINIUM_Z = 0xFFFE,		//0x2B3
	ITEM_KOMMONIUM_Z = 0xFFFE,		//0x2B4
	ITEM_LUNALIUM_Z = 0xFFFE,		//0x2B5
	ITEM_LYCANIUM_Z = 0xFFFE,		//0x2B6
	ITEM_MARSHADIUM_Z = 0xFFFE,		//0x2B7
	ITEM_MEWNIUM_Z = 0xFFFE,			//0x2B8
	ITEM_MIMIKIUM_Z = 0xFFFE,		//0x2B9
	ITEM_PIKANIUM_Z = 0xFFFE,		//0x2BA
	ITEM_PIKASHUNIUM_Z = 0xFFFE,		//0x2BB
	ITEM_PRIMARIUM_Z = 0xFFFE,		//0x2BC
	ITEM_SNORLIUM_Z = 0xFFFE,		//0x2BD
	ITEM_SOLGANIUM_Z = 0xFFFE,		//0x2BE
	ITEM_TAPUNIUM_Z = 0xFFFE,		//0x2BF
};

//Sword & Shield Hold Items
#define ITEM_EJECT_PACK 0xFFFE
#define ITEM_ROOM_SERVICE 0xFFFE
#define ITEM_BLUNDER_POLICY 0xFFFE
#define ITEM_HEAVY_DUTY_BOOTS 0xFFFE
#define ITEM_UTILITY_UMBRELLA 0xFFFE
#define ITEM_THROAT_SPRAY 0x48 //0x2C5 Come Back

#define ITEMS_COUNT (ITEM_N_LUNARIZER + 1)
